# Generated by Django 3.2.4 on 2021-07-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_account_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='description',
            new_name='type',
        ),
    ]
